name: "Validate Gradle Wrapper"
on: [push, pull_request, fork]

jobs:
  validation:
    name: "Validation"
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
